a = set()
print(type(a))
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the second number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
b = int(input("Enter the first number : "))
a.add(b)
print(a)